repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Run autoflake
        entry: autoflake .
        language: system
        types: [python]

      - id: isort
        name: Run isort
        entry: isort .
        language: system
        types: [python]

      - id: black
        name: Run black
        entry: black .
        language: system
        types: [python]

      - id: flake8
        name: Run flake8
        entry: flake8 .
        language: system
        types: [python]
